export enum ErrorCodes {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNIQUE_CONSTRAINT = 'UNIQUE_CONSTRAINT',
  ERROR_GENERATING_TOKEN = 'ERROR_GENERATING_TOKEN',
  MODEL_NOT_FOUND = 'MODEL_NOT_FOUND',
  INVALID_ID_FORMAT = 'INVALID_ID_FORMAT',
  VALIDATION_ENTITY_NOT_FOUND = 'VALIDATION_ENTITY_NOT_FOUND',
  DATABASE_UNIQUE_CONSTRAINT_VIOLATION = 'DATABASE_UNIQUE_CONSTRAINT_VIOLATION',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  POPULATION_ERROR = 'POPULATION_ERROR',
}
